version: '3'

services:
  node-app:
    build: .
    image: mh-survey
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/survey
    ports:
      - '4088:4088'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/mh-survey
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27018:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
